name: Event Management WebApp CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    AZURE_WEBAPP_NAME: 'event-management-service'
    AZURE_WEBAPP_PACKAGE_PATH: '.'
    AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    DOTNET_VERSION: '9.x'
    SOLUTION_FILE: 'EventManagement.Server/EventManagement.Server.sln'
    API_PROJECT_FILE: 'EventManagement.Server/EventManagement.Server.csproj'
    PUBLISH_DIR: './publish'

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up .NET
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore dependencies
              run: dotnet restore ${{ env.SOLUTION_FILE }}

            - name: Build solution
              run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

            - name: Publish API
              run: dotnet publish ${{ env.API_PROJECT_FILE }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}
            
            - name: Publish Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: webapp
                path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
            
    deploy:
        name: Deploy to Azure
        runs-on: ubuntu-latest
        needs: [build-and-test]

        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                name: webapp
                path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
            
            - name: Deploy to Azure
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}