// <auto-generated />
using System;
using EventManagement.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventManagement.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250515221539_update_event_tags_table")]
    partial class update_event_tags_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventManagement.Server.Models.BookingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("BookingStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Booked"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("EventManagement.Server.Models.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BookingStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfBookedTickets")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UsersAuth0UserId")
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("EventId");

                    b.HasIndex("UsersAuth0UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EventManagement.Server.Models.EventStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("EventStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Ongoing"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("EventManagement.Server.Models.EventTags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TagId");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("EventManagement.Server.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UsersAuth0UserId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UsersAuth0UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventManagement.Server.Models.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventsId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UsersAuth0UserId")
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EventsId");

                    b.HasIndex("UsersAuth0UserId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("EventManagement.Server.Models.Tags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tag = "Music"
                        },
                        new
                        {
                            Id = 2,
                            Tag = "Sports"
                        },
                        new
                        {
                            Id = 3,
                            Tag = "Arts"
                        },
                        new
                        {
                            Id = 4,
                            Tag = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            Tag = "Food"
                        },
                        new
                        {
                            Id = 6,
                            Tag = "Travel"
                        },
                        new
                        {
                            Id = 7,
                            Tag = "Health"
                        },
                        new
                        {
                            Id = 8,
                            Tag = "Education"
                        },
                        new
                        {
                            Id = 9,
                            Tag = "Environment"
                        },
                        new
                        {
                            Id = 10,
                            Tag = "Community"
                        });
                });

            modelBuilder.Entity("EventManagement.Server.Models.Users", b =>
                {
                    b.Property<string>("Auth0UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RolesEnum")
                        .HasColumnType("integer");

                    b.HasKey("Auth0UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventManagement.Server.Models.Bookings", b =>
                {
                    b.HasOne("EventManagement.Server.Models.BookingStatus", "BookingStatus")
                        .WithMany()
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Server.Models.Events", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Server.Models.Users", null)
                        .WithMany("Bookings")
                        .HasForeignKey("UsersAuth0UserId");

                    b.Navigation("BookingStatus");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventManagement.Server.Models.EventTags", b =>
                {
                    b.HasOne("EventManagement.Server.Models.Events", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Server.Models.Tags", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("EventManagement.Server.Models.Events", b =>
                {
                    b.HasOne("EventManagement.Server.Models.EventStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Server.Models.Users", null)
                        .WithMany("Events")
                        .HasForeignKey("UsersAuth0UserId");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("EventManagement.Server.Models.Images", b =>
                {
                    b.HasOne("EventManagement.Server.Models.Events", null)
                        .WithMany("Images")
                        .HasForeignKey("EventsId");

                    b.HasOne("EventManagement.Server.Models.Users", null)
                        .WithMany("Images")
                        .HasForeignKey("UsersAuth0UserId");
                });

            modelBuilder.Entity("EventManagement.Server.Models.Events", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("EventManagement.Server.Models.Users", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Events");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
